#FROM ubuntu:22.04
#RUN apt-get update
#RUN apt-get install -y nginx
#RUN echo "\ndaemon off;" >> /etc/nginx/nginx.config
#RUN echo "<h1>Hello, Docker V1</h1>" > /var/www/html/index.html
#EXPOSE 80
#CMD ["nginx"]

FROM nginx
RUN  echo "<h1>Hello, Docker V2 by jingyeong</h1>" > /usr/share/nginx/html/index.html