# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.host_name = "nginx-server"
    config.vm.provision "shell", inline: <<-SHELL
        sudo swapoff -a


        sudo sed -i.bak -r 's/(.+ swap .+)/#\1/' /etc/fstab


        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config  
        sudo systemctl restart sshd


        sudo apt-get update
        sudo apt-get install -y nginx


        echo "<h1>Hello, World!</h1>" | sudo tee /var/www/html/index.html
    SHELL
end
